local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 20.0
  publish_frequency: 10.0
  static_map: true
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.25
  transform_tolerance: 0.5
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
